# Generated by Django 4.2.10 on 2024-12-16 15:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('article', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(5, 'Rate points cannot be greater than 5')])),
                ('ratings', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.CharField(choices=[('XXS', '2Extra Small'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2Extra Large')], max_length=3)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=6)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cloth',
                'verbose_name_plural': 'Clothes',
            },
        ),
    ]
