# Generated by Django 4.2.10 on 2024-12-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_clothes_sex_shoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Black', 'Black'), ('White', 'White'), ('Gray', 'Gray')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='shoes',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='size',
            field=models.CharField(choices=[('XXS', '2Extra Small'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2Extra Large')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size',
            field=models.IntegerField(choices=[(30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50)], null=True),
        ),
    ]
