# Generated by Django 4.2.10 on 2024-12-18 11:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('goods', '0004_alter_clothes_seller_alter_shoes_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skirts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('article', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(5, 'Rate points cannot be greater than 5')])),
                ('reviews', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('season', models.CharField(choices=[('Summer', 'Summer'), ('Demi-season', 'Demi-season'), ('Winter', 'Winter')], max_length=11)),
                ('style', models.CharField(choices=[('Classic', 'Classic'), ('Casual', 'Casual'), ('Street', 'Street'), ('Mini', 'Minimalist')], max_length=10)),
                ('size', models.CharField(choices=[('XXS', '2Extra Small'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2Extra Large')], max_length=3, null=True)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Black', 'Black'), ('White', 'White'), ('Gray', 'Gray')], max_length=5, null=True)),
                ('sex', models.CharField(default='Female', editable=False, max_length=6)),
                ('length', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MaxValueValidator(200)], verbose_name='length in cantimeters')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'verbose_name': 'Skirt',
                'db_table': 'Skirts',
            },
        ),
        migrations.CreateModel(
            name='T_shirts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('article', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(5, 'Rate points cannot be greater than 5')])),
                ('reviews', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('season', models.CharField(choices=[('Summer', 'Summer'), ('Demi-season', 'Demi-season'), ('Winter', 'Winter')], max_length=11)),
                ('style', models.CharField(choices=[('Classic', 'Classic'), ('Casual', 'Casual'), ('Street', 'Street'), ('Mini', 'Minimalist')], max_length=10)),
                ('size', models.CharField(choices=[('XXS', '2Extra Small'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2Extra Large')], max_length=3, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6, null=True)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Black', 'Black'), ('White', 'White'), ('Gray', 'Gray')], max_length=5, null=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'verbose_name': 'T-shirt',
                'db_table': 'T-shirts',
            },
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Clothes',
        ),
        migrations.DeleteModel(
            name='Shoes',
        ),
    ]
